import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hello World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: //dashboard,
Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between items-center p-2 bg-blue-600 text-white">
          <Link href={'/'} className="text-3xl font-bold ">BLOGY</Link>
          <Link
            href="/create"
            className="text-blue-400 p-2 bg-white rounded-md font-medium text-sm"
          >
            Crete new blog
          </Link>
        </nav>

        <div className="px-2">{children}</div>
      </body>
    </html>
  );
}
