import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hello World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  dashboard,

}: Readonly<{
  children: React.ReactNode;
  dashboard:React.ReactNode;

}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="underline mx-4 space-x-4">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/settings">Settings</Link>
          {/*  <Link href="/settings/profile">Profile</Link> */}
        </nav>
        {children}
        {dashboard}
      </body>
    </html>
  );
}
